- name: "instalación dhcp"
  apt:
    pkg: isc-dhcp-server

- name: "definir insterfaces"
  template:
    src: isc-dhcp-server
    dest: /etc/default/isc-dhcp-server
    owner: root
    group: root
    mode: 0644
  notify:
    - restart dhcp

- name: "configuración dhcp"
  template:
    src: dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart dhcp

